"""v1_5_auth

Revision ID: 0922a0ae460c
Revises: 
Create Date: 2024-11-17 20:16:47.909404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0922a0ae460c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    op.drop_constraint('ix_users_email', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint('ix_users_username', 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint('ix_users_username', 'users', ['username'])
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('ix_users_email', 'users', ['email'])
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
