"""v1.3

Revision ID: 7d33e02655fb
Revises: 966d59ce6f7e
Create Date: 2024-10-14 14:31:04.275217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d33e02655fb'
down_revision: Union[str, None] = '966d59ce6f7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('themes', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('themes', 'description')
    # ### end Alembic commands ###
