"""v1.1

Revision ID: db4a57f185da
Revises: e5c149106208
Create Date: 2024-10-14 10:47:11.326063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db4a57f185da'
down_revision: Union[str, None] = 'e5c149106208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiments', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'experiments', 'users', ['creator_id'], ['id'])
    op.add_column('themes', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'themes', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'themes', type_='foreignkey')
    op.drop_column('themes', 'creator_id')
    op.drop_constraint(None, 'experiments', type_='foreignkey')
    op.drop_column('experiments', 'creator_id')
    # ### end Alembic commands ###
